# Importing all dependencies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.models import load_model
import joblib
import pickle

In [4]:
tf.__version__

'2.15.0'

# Loading Dataset

In [5]:
dataset=pd.read_csv(r'C:\Users\liles\Downloads\Farmer-Yield-Analysis-Prediction-main\Farmer-Yield-Analysis-Prediction-main\crop_recommendation.csv')
dataset = dataset.drop(columns='humidity') 

In [6]:
dataset

N   P   K  temperature        ph    rainfall   label
0      90  42  43    20.879744  6.502985  202.935536    rice
1      85  58  41    21.770462  7.038096  226.655537    rice
2      60  55  44    23.004459  7.840207  263.964248    rice
3      74  35  40    26.491096  6.980401  242.864034    rice
4      78  42  42    20.130175  7.628473  262.717340    rice
...   ...  ..  ..          ...       ...         ...     ...
2195  107  34  32    26.774637  6.780064  177.774507  coffee
2196   99  15  27    27.417112  6.086922  127.924610  coffee
2197  118  33  30    24.131797  6.362608  173.322839  coffee
2198  117  32  34    26.272418  6.758793  127.175293  coffee
2199  104  18  30    23.603016  6.779833  140.937041  coffee

[2200 rows x 7 columns]

In [7]:
x=dataset.iloc[:, :-1].values


In [8]:
print(x)

[[ 90.          42.          43.          20.87974371   6.50298529
  202.9355362 ]
 [ 85.          58.          41.          21.77046169   7.03809636
  226.6555374 ]
 [ 60.          55.          44.          23.00445915   7.84020714
  263.9642476 ]
 ...
 [118.          33.          30.          24.13179691   6.36260785
  173.3228386 ]
 [117.          32.          34.          26.2724184    6.75879255
  127.1752928 ]
 [104.          18.          30.          23.60301571   6.77983261
  140.9370415 ]]


In [9]:
y=dataset.iloc[:, -1].values
y = y.reshape(-1, 1)

In [10]:
print(y)

[['rice']
 ['rice']
 ['rice']
 ...
 ['coffee']
 ['coffee']
 ['coffee']]


# Crop Prediction Using ANN Model



In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [12]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False, handle_unknown='ignore').fit(y_train)
y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
list_of_crops = list(encoder.categories_)

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler().fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

In [15]:
print(x_train)

[[-0.64463185  2.00512125  2.96466347 -0.81644358 -0.4785779   0.23692732]
 [ 0.81334894 -0.52889759 -0.2035231  -0.35345966 -0.18240887  0.84590226]
 [ 1.05634574  0.1649409  -0.26219322 -0.25621148  0.82415091  1.29625399]
 ...
 [-0.42863469  0.31577536 -0.65332736  0.58919451  0.03555503 -0.61777686]
 [-0.32063612  0.34594225 -0.4968737  -0.01933801  1.59909782 -1.13413007]
 [-0.99562722 -0.95123406 -0.7706676  -1.65789642  0.09231399  0.1609325 ]]


In [16]:
print(x_test)

[[ 1.4613404  -1.19256918  0.03115739  0.13686485 -0.07136897 -0.79662206]
 [ 1.08334538 -1.25290297 -0.04706944 -0.17748811 -0.17040403 -1.00213923]
 [-0.99562722  2.03528814  3.02333359 -3.16429901 -0.41466753 -0.52833787]
 ...
 [ 1.78533613  0.07444023 -0.65332736  0.09232143  1.18019647 -0.26283457]
 [-0.64463185  0.31577536 -0.53598712  1.4635514   1.41166076 -0.54269489]
 [-0.53663327  2.30679015  2.92555005 -0.7466762  -1.21088837  0.29771091]]


In [17]:
x_train.shape


(1760, 6)

In [18]:
y_train.shape

(1760, 22)

In [19]:
ann = tf.keras.models.Sequential()

In [20]:
ann.add(tf.keras.layers.Dense(units=32, activation = 'relu'))

In [21]:
ann.add(tf.keras.layers.Dense(units=128, activation = 'relu'))

In [22]:
ann.add(tf.keras.layers.Dense(units = 22, activation = 'softmax'))

In [23]:
ann.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [24]:
ann.fit(x_train, y_train, batch_size =32, epochs = 100)

Epoch 1/100


55/55 [==============================] - 6s 5ms/step - loss: 2.6761 - accuracy: 0.2960
Epoch 2/100
55/55 [==============================] - 0s 4ms/step - loss: 1.7253 - accuracy: 0.6500
Epoch 3/100
55/55 [==============================] - 0s 4ms/step - loss: 0.9848 - accuracy: 0.8068
Epoch 4/100
55/55 [==============================] - 0s 3ms/step - loss: 0.6653 - accuracy: 0.8432
Epoch 5/100
55/55 [==============================] - 0s 3ms/step - loss: 0.5139 - accuracy: 0.8744
Epoch 6/100
55/55 [==============================] - 0s 3ms/step - loss: 0.4221 - accuracy: 0.8972
Epoch 7/100
55/55 [==============================] - 0s 5ms/step - loss: 0.3583 - accuracy: 0.9051
Epoch 8/100
55/55 [==============================] - 0s 5ms/step - loss: 0.3153 - accuracy: 0.9136
Epoch 9/100
55/55 [==============================] - 0s 5ms/step - loss: 0.2858 - accuracy: 0.9170
Epoch 10/100
55/55 [==============================] - 0s 4ms/step - loss: 0.2580 - accuracy: 0.9233
Epoch 1

In [25]:
prediction = ann.predict(sc.transform([[80, 46, 21, 24, 5.6, 72]]))

1/1 [==============================] - 1s 586ms/step


In [33]:
#prediction = prediction.tolist()

In [26]:
list_of_crops[0]

array(['apple', 'banana', 'blackgram', 'chickpea', 'coconut', 'coffee',
       'cotton', 'grapes', 'jute', 'kidneybeans', 'lentil', 'maize',
       'mango', 'mothbeans', 'mungbean', 'muskmelon', 'orange', 'papaya',
       'pigeonpeas', 'pomegranate', 'rice', 'watermelon'], dtype=object)

In [27]:
def crop_map(prediction,lst_crops):
  crop_pred_dic = {}
  for i,j in zip(prediction[0],lst_crops[0]):
    crop_pred_dic[j] = i

  return crop_pred_dic


In [28]:
crop_pred_dic = crop_map(prediction,list_of_crops)

In [29]:
sorted_top_crop = sorted(crop_pred_dic.items(), key=lambda x:x[1])
print(sorted_top_crop[-1][0])

maize


# KNN Model

In [38]:
from sklearn.model_selection import train_test_split
x_train_k, x_test_k, y_train_k, y_test_k = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [39]:
x_train_k = sc.transform(x_train_k)
x_test_k = sc.transform(x_test_k)

In [40]:
y_train_k

array([['apple'],
       ['jute'],
       ['jute'],
       ...,
       ['blackgram'],
       ['lentil'],
       ['orange']], dtype=object)

In [41]:
from sklearn.preprocessing import LabelEncoder

le_encoder = LabelEncoder()
y_train_k = le_encoder.fit_transform(y_train_k)
y_test_k = encoder.transform(y_test_k)

C:\Users\Owner\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [42]:
le_name_mapping = dict(zip(le_encoder.classes_, le_encoder.transform(le_encoder.classes_)))

In [43]:
le_name_mapping

{'apple': 0,
 'banana': 1,
 'blackgram': 2,
 'chickpea': 3,
 'coconut': 4,
 'coffee': 5,
 'cotton': 6,
 'grapes': 7,
 'jute': 8,
 'kidneybeans': 9,
 'lentil': 10,
 'maize': 11,
 'mango': 12,
 'mothbeans': 13,
 'mungbean': 14,
 'muskmelon': 15,
 'orange': 16,
 'papaya': 17,
 'pigeonpeas': 18,
 'pomegranate': 19,
 'rice': 20,
 'watermelon': 21}

In [44]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors = 100, weights = 'uniform', algorithm = 'auto', metric='minkowski', p =2)

In [45]:
clf.fit(x_train_k, y_train_k)

KNeighborsClassifier(n_neighbors=100)

In [46]:
print(clf.predict(sc.transform([[80, 46, 21, 24, 5.6, 72]])))

[11]


In [47]:
neighbors = clf.kneighbors(sc.transform([[80, 46, 21, 24, 5.6, 72]]), return_distance=False)

In [48]:
neighbors

array([[ 999, 1470,  802,  456, 1180,  694, 1541,   12,  594, 1399, 1239,
         561, 1014, 1336,  431,   69,  343,  939, 1061,  329,  956, 1484,
         344, 1483, 1677, 1549,  157,   10,  869,  440,  997, 1073,  603,
        1110, 1637, 1282, 1697,  227,  221,  163, 1060, 1726, 1527, 1186,
         800, 1548,  378,  173,   26,  927, 1132, 1512, 1622,  721, 1553,
         863,   74, 1630,  544,  140, 1611,  206,  966,  191,  970,  290,
        1515,  629,  381,  386,  507, 1140,  302, 1204, 1359,  649, 1366,
         134,  374, 1718, 1236, 1273, 1545, 1168, 1286,  126,   83,  503,
         954,  516, 1431, 1030, 1731,  405, 1690,  165,  274,  710, 1466,
         521]], dtype=int64)

In [49]:
unique_recommended_values = np.unique(y_train_k[neighbors][0])

In [50]:
unique_recommended_values

array([ 1,  5,  6,  9, 11, 17, 21])

In [51]:
key_list = list(le_name_mapping.keys())
val_list = list(le_name_mapping.values())
recommended_crop_lst = []
 
for each in unique_recommended_values:  
  
  position = val_list.index(each)
  recommended_crop_lst.append(key_list[position])

In [52]:
recommended_crop_lst

['banana', 'coffee', 'cotton', 'kidneybeans', 'maize', 'papaya', 'watermelon']

In [53]:
# test_point = sc.transform([[86, 56, 42, 26.99, 6.2, 254]])

In [54]:
# neighbors = clf.kneighbors(test_point, return_distance=False)

In [55]:
# neighbors

In [56]:
# neighbor_classes = y[neighbors[0]]

# Save the Model

In [58]:
# save the model

ann.save(r"C:\Users\liles\Downloads\Farmer-Yield-Analysis-Prediction-main\Farmer-Yield-Analysis-Prediction-main\model files\ann_model.h5")
joblib.dump(sc, r"C:\Users\liles\Downloads\Farmer-Yield-Analysis-Prediction-main\Farmer-Yield-Analysis-Prediction-main\model files\clf_model.sav") 


filename = r"C:\Users\liles\Downloads\Farmer-Yield-Analysis-Prediction-main\Farmer-Yield-Analysis-Prediction-main\model files\clf_model.sav"
pickle.dump(KNeighborsClassifier, open(filename, 'wb'))

In [60]:
joblib.dump(y_train_k,r"C:\Users\liles\Downloads\Farmer-Yield-Analysis-Prediction-main\Farmer-Yield-Analysis-Prediction-main\model files\y_train_k.joblib")

['C:\\Users\\Owner\\Tri Nit\\model files\\y_train_k.joblib']

In [61]:
joblib.dump(x_train_k,r"C:\Users\liles\Downloads\Farmer-Yield-Analysis-Prediction-main\Farmer-Yield-Analysis-Prediction-main\model files\x_train_k.joblib")

['C:\\Users\\Owner\\Tri Nit\\model files\\x_train_k.joblib']